services:
  postgres:
    container_name: chorechart-db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-adminpass}
      POSTGRES_DB: ${POSTGRES_DB:-chorechart_python}
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-chorechart_python}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: chorechart-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./server/db/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    restart: unless-stopped

  server:
    container_name: chorechart-api
    build:
      context: ./server
      target: development
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONPATH=/app
      - API_PORT=4000
      - API_HOST=0.0.0.0
      - CORS_ORIGIN=http://localhost:3000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-adminpass}@postgres:5432/${POSTGRES_DB:-chorechart_python}
    command: uvicorn app.main:app --host 0.0.0.0 --port 4000 --reload
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    container_name: chorechart-ui
    build:
      context: ./ui
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  pgadmin_data:
